server:
  port: 8080

spring:
  application:
    name: api-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # ✅ Eureka에 등록된 서비스 이름 기반으로 라우팅
          lower-case-service-id: true

      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservation/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stocks/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/tickets/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka