server:
  port: 8082

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_system
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true